#
#
# Title:        Makefile.Test
# Project:	Mdb
# Desc:
# 
#   
# 
# Notes:
# 
# Author:	Paul Houghton - (paul.houghton@wcom.com)
# Created:	07/13/97 06:41
#
# Revision History: (See end of file for Revision Log)
#
#   Last Mod By:    $Author$
#   Last Mod:	    $Date$
#   Version:	    $Revision$
#
#   $Id$
# 

ARCH_INC	= -I$(PRJ_TOPDIR)/src/arch/$(arch)/test
MDB_SRC_INC	= -I$(PRJ_TOPDIR)/src/Mdb

MDB_SRC_LDIR	= -L$(PRJ_TOPDIR)/src/Mdb

ARCH_DEFAULT_LD_LIBS = -lStdC++
ARCH_DEBUG_LD_LIBS = -lStdC++

#
# $Log$
# Revision 1.1  1997/07/14 10:55:14  houghton
# Initial Version.
#
#

# Local Variables:
# mode:makefile
# End:
