#
# Title:        Makefile.Test
# Project:	Mdb
# Desc:
# 
#   
# 
# Notes:
# 
# Author:	Paul A. Houghton - (paul.houghton@wcom.com)
# Created:	07/18/97 06:19
#
# Revision History: (See end of file for Revision Log)
#
#   Last Mod By:    $Author$
#   Last Mod:	    $Date$
#   Version:	    $Revision$
#
#   $Id$
# 

ARCH_INC	= -I$(PRJ_TOPDIR)/src/arch/$(arch)/test
MDB_SRC_INC	= -I$(PRJ_TOPDIR)/src/Mdb

MDB_SRC_LDIR	= -L$(PRJ_TOPDIR)/src/Mdb

ARCH_DEFAULT_LD_LIBS = 
ARCH_DEBUG_LD_LIBS = 

#
# $Log$
# Revision 4.1  2001/07/27 00:57:44  houghton
# Change Major Version to 4
#
# Revision 2.2  1999/11/04 17:27:14  houghton
# Removed libStdC++ (not needed.).
#
# Revision 2.1  1997/09/21 19:21:43  houghton
# Changed version to 2
#
# Revision 1.1  1997/07/19 10:34:14  houghton
# Initial Version.
#
#

# Local Variables:
# mode:makefile
# End:
