#
# Title:        Makefile
# Project:	Mdb
# Desc:
# 
#   
# 
# Notes:
# 
# Author:	Paul A. Houghton - (paul.houghton@wcom.com)
# Created:	07/02/99 06:25
#
# Revision History: (See end of file for Revision Log)
#
#   Last Mod By:    $Author$
#   Last Mod:	    $Date$
#   Version:	    $Revision$
#
#   $Id$
# 


install_docs:

clean realclean:


#
# $Log$
# Revision 1.2  1999/10/30 11:50:40  houghton
# Changed install_doc to install_docs.
#
# Revision 1.1  1999/07/06 10:11:28  houghton
# Initial Version.
#
#

# Local Variables:
# mode:makefile
# End:
